version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "sleep 5 &&
      poetry run gunicorn -k uvicorn.workers.UvicornWorker -w 1
      -t 300 -b 0.0.0.0:8000 src.api.main:app"